- name: Setup
  hosts: home
  tasks:
    - name: install pip packages
      pip: name={{ item }}
      with_items:
        - virtualenv

    - name: git clone
      git:
        repo: git@github.com:azclub/pingpong.git
        dest: "{{ project_dir }}"
        clone: yes
        force: yes
        version: phase1

    - name: setup
      pip:
        requirements: "{{ project_dir }}/requirements.txt"
        virtualenv: "{{ project_dir }}/venv"

    # - name: run python command
    # - command: source {{ project_dir }}/venv/bin/activate
