- name: Setup
  hosts: home
  tasks:
    - name: install pip packages
      pip: name={{ item }}
      with_items:
        - virtualenv
        - virtualenvwrapper

    - name: create directories
      file: path={{ virtualenv_dir }} state=directory
      file: path={{ project_dir }} state=directory

    - name: setup
      pip:
        requirements: "{{ project_dir }}/requirements.txt"
        virtualenv: "{{ virtualenv_dir }}"
        virtualenv_python: python2.7

